"""initial schema

The eleven tables in docs/context/data-model.md, as one migration.

Three things in here are deliberate and easy to undo by accident:

- **The four unique indexes carry `postgresql_where=deleted_at IS NULL`.** They
  are partial so a soft-deleted row stops reserving its identity. Without the
  clause, a deleted class holds its join code forever and a deleted user can
  neither sign in again nor be re-created.
- **Every foreign key is ON DELETE CASCADE**, except `tutor_message.attempt_id`
  which is SET NULL because an opening Prompt legitimately answers no attempt.
  The cascades are what make a study participant's withdrawal one statement
  instead of eleven.
- **Timestamps are TIMESTAMPTZ and the two token/warning columns are JSONB.**

Revision ID: 8f3c1a2b4d5e
Revises:
Create Date: 2026-09-03
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

revision: str = '8f3c1a2b4d5e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_sub', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('participant_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('instructor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('join_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instructor_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('core_component',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reading_id', sa.Uuid(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['reading.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrolment',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reading_assignment',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reading_id', sa.Uuid(), nullable=False),
    sa.Column('class_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reading_id'], ['reading.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('reading_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_step', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rubric_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tutor_prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assessment_prompt_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['reading_id'], ['reading.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attempt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.String(length=16), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('response_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.String(length=8), nullable=False),
    sa.Column('model_verdict', sa.String(length=8), nullable=True),
    sa.Column('raw_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor_message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('step', sa.String(length=16), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('moves', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criterion_judgment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('criterion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_deleted_at'), 'app_user', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_app_user_participant_identifier'), 'app_user', ['participant_identifier'], unique=False)
    op.create_index(op.f('ix_app_user_role'), 'app_user', ['role'], unique=False)
    op.create_index('uq_app_user_google_sub', 'app_user', ['google_sub'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_class_deleted_at'), 'class', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_class_instructor_id'), 'class', ['instructor_id'], unique=False)
    op.create_index('uq_class_join_code', 'class', ['join_code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_reading_deleted_at'), 'reading', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_reading_uploaded_by'), 'reading', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_core_component_reading_id'), 'core_component', ['reading_id'], unique=False)
    op.create_index(op.f('ix_enrolment_class_id'), 'enrolment', ['class_id'], unique=False)
    op.create_index(op.f('ix_enrolment_deleted_at'), 'enrolment', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_enrolment_student_id'), 'enrolment', ['student_id'], unique=False)
    op.create_index('uq_enrolment_student_class', 'enrolment', ['student_id', 'class_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_reading_assignment_class_id'), 'reading_assignment', ['class_id'], unique=False)
    op.create_index(op.f('ix_reading_assignment_deleted_at'), 'reading_assignment', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_reading_assignment_reading_id'), 'reading_assignment', ['reading_id'], unique=False)
    op.create_index('uq_reading_assignment', 'reading_assignment', ['reading_id', 'class_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_session_reading_id'), 'session', ['reading_id'], unique=False)
    op.create_index(op.f('ix_session_status'), 'session', ['status'], unique=False)
    op.create_index(op.f('ix_session_student_id'), 'session', ['student_id'], unique=False)
    op.create_index(op.f('ix_attempt_session_id'), 'attempt', ['session_id'], unique=False)
    op.create_index(op.f('ix_attempt_step'), 'attempt', ['step'], unique=False)
    op.create_index('uq_attempt_session_step_number', 'attempt', ['session_id', 'step', 'attempt_number'], unique=True)
    op.create_index(op.f('ix_assessment_attempt_id'), 'assessment', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_assessment_verdict'), 'assessment', ['verdict'], unique=False)
    op.create_index(op.f('ix_tutor_message_attempt_id'), 'tutor_message', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_tutor_message_session_id'), 'tutor_message', ['session_id'], unique=False)
    op.create_index(op.f('ix_criterion_judgment_assessment_id'), 'criterion_judgment', ['assessment_id'], unique=False)
    op.create_index('ix_criterion_judgment_criterion_passed', 'criterion_judgment', ['criterion', 'passed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_criterion_judgment_assessment_id'), table_name='criterion_judgment')
    op.drop_index('ix_criterion_judgment_criterion_passed', table_name='criterion_judgment')
    op.drop_index(op.f('ix_tutor_message_attempt_id'), table_name='tutor_message')
    op.drop_index(op.f('ix_tutor_message_session_id'), table_name='tutor_message')
    op.drop_index(op.f('ix_assessment_attempt_id'), table_name='assessment')
    op.drop_index(op.f('ix_assessment_verdict'), table_name='assessment')
    op.drop_index(op.f('ix_attempt_session_id'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_step'), table_name='attempt')
    op.drop_index('uq_attempt_session_step_number', table_name='attempt')
    op.drop_index(op.f('ix_session_reading_id'), table_name='session')
    op.drop_index(op.f('ix_session_status'), table_name='session')
    op.drop_index(op.f('ix_session_student_id'), table_name='session')
    op.drop_index(op.f('ix_reading_assignment_class_id'), table_name='reading_assignment')
    op.drop_index(op.f('ix_reading_assignment_deleted_at'), table_name='reading_assignment')
    op.drop_index(op.f('ix_reading_assignment_reading_id'), table_name='reading_assignment')
    op.drop_index('uq_reading_assignment', table_name='reading_assignment', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_enrolment_class_id'), table_name='enrolment')
    op.drop_index(op.f('ix_enrolment_deleted_at'), table_name='enrolment')
    op.drop_index(op.f('ix_enrolment_student_id'), table_name='enrolment')
    op.drop_index('uq_enrolment_student_class', table_name='enrolment', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_core_component_reading_id'), table_name='core_component')
    op.drop_index(op.f('ix_reading_deleted_at'), table_name='reading')
    op.drop_index(op.f('ix_reading_uploaded_by'), table_name='reading')
    op.drop_index(op.f('ix_class_deleted_at'), table_name='class')
    op.drop_index(op.f('ix_class_instructor_id'), table_name='class')
    op.drop_index('uq_class_join_code', table_name='class', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_app_user_deleted_at'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_participant_identifier'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_role'), table_name='app_user')
    op.drop_index('uq_app_user_google_sub', table_name='app_user', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('criterion_judgment')
    op.drop_table('tutor_message')
    op.drop_table('assessment')
    op.drop_table('attempt')
    op.drop_table('session')
    op.drop_table('reading_assignment')
    op.drop_table('enrolment')
    op.drop_table('core_component')
    op.drop_table('reading')
    op.drop_table('class')
    op.drop_table('app_user')
    # ### end Alembic commands ###
